var survey_metadata = {
  Instrument: {
    $CAL_DUE: "2025-05-16",
    $DNA: "002C250966008854",
    $FIRMWARE_VERSION: "4.7 (Herbillette)",
    $HARDWARE_VERSION: 8,
    $SELF_CHECK: "0x00000000",
    $SERIAL: "00228",
    $ULTRA_COLOUR_SCHEME: "$ULTRA_SCHEME_AMPLITUDE",
    "Cable PD PILC thresholds": { Amber: 2500, Red: 7000 },
    "Cable PD XLPE thresholds": { Amber: 250, Red: 500 },
    "TEV Thresholds": { Amber: 20, Red: 29 },
    "Ultrasonic thresholds": { Red: 6 },
  },
  StartTimeUtc: "20000101T004756Z",
  "Survey Name": "19991231T194756",
  Trend: [{ date: "19991231T194756" }],
  survey_fields: [
    {
      fields: [
        {
          data: "",
          fieldname: "$JOB_NO",
          mandatory: false,
          options: [],
          readonly: false,
          validation: "",
          validation_message: "",
        },
        {
          data: "",
          fieldname: "$ENGINEER_NAME",
          mandatory: false,
          options: [],
          readonly: false,
          validation: "",
          validation_message: "",
        },
      ],
      group: "$GROUP_JOB",
    },
    {
      fields: [
        {
          data: "Example Sub",
          fieldname: "$SUB_NAME",
          mandatory: false,
          options: [],
          readonly: false,
          validation: "",
          validation_message: "",
        },
        {
          data: "$INDOOR",
          fieldname: "$SUB_TYPE",
          mandatory: false,
          options: [],
          readonly: false,
          validation: "",
          validation_message: "",
        },
        {
          data: "$L1_L2_L3",
          fieldname: "$CABLE_NAMING",
          mandatory: false,
          options: [],
          readonly: false,
          validation: "",
          validation_message: "",
        },
      ],
      group: "$GROUP_SUB",
    },
    {
      fields: [
        {
          data: "Example",
          fieldname: "$SWGR_MNFR",
          mandatory: false,
          options: [],
          readonly: false,
          validation: "",
          validation_message: "",
        },
        {
          data: "Example",
          fieldname: "$SWGR_TYPE",
          mandatory: false,
          options: [],
          readonly: false,
          validation: "",
          validation_message: "",
        },
        {
          data: "",
          fieldname: "$SWGR_INSTALL_DATE",
          mandatory: false,
          options: [],
          readonly: false,
          validation: "",
          validation_message: "",
        },
        {
          data: "36",
          fieldname: "$SWGR_RATED_V",
          mandatory: false,
          options: [],
          readonly: false,
          validation: "",
          validation_message: "",
        },
        {
          data: "33",
          fieldname: "$SWGR_OPERATING_V",
          mandatory: false,
          options: [],
          readonly: false,
          validation: "",
          validation_message: "",
        },
        {
          data: "$INSU_AIR",
          fieldname: "$BUSBAR_INSU",
          mandatory: false,
          options: [],
          readonly: false,
          validation: "",
          validation_message: "",
        },
      ],
      group: "$GROUP_SWGR",
    },
    {
      fields: [
        {
          data: "",
          fieldname: "$BACK_METAL_DB",
          mandatory: false,
          options: [],
          readonly: false,
          validation: "",
          validation_message: "",
        },
        {
          data: "",
          fieldname: "$BACK_METAL_PPC",
          mandatory: false,
          options: [],
          readonly: false,
          validation: "",
          validation_message: "",
        },
        {
          data: "",
          fieldname: "$BACK_AIR_DB",
          mandatory: false,
          options: [],
          readonly: false,
          validation: "",
          validation_message: "",
        },
        {
          data: "",
          fieldname: "$BACK_AIR_PPC",
          mandatory: false,
          options: [],
          readonly: false,
          validation: "",
          validation_message: "",
        },
        {
          data: "",
          fieldname: "$TEMPERATURE_C",
          mandatory: false,
          options: [],
          readonly: false,
          validation: "",
          validation_message: "",
        },
        {
          data: "",
          fieldname: "$HUMIDITY",
          mandatory: false,
          options: [],
          readonly: false,
          validation: "",
          validation_message: "",
        },
      ],
      group: "$GROUP_CONDITIONS",
    },
  ],
};
